# Numpy Array


In [286]:
import numpy as np

# Vector : 
  - Vector is one Dimension is a single array
# Matrix : 
  - Matrix is a Multi Dimension Array 

## Basic Array Creation

In [290]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [291]:
a = [1,2,3.5,'Ahsan',5]
a

[1, 2, 3.5, 'Ahsan', 5]

In [292]:
np.array(a)

array(['1', '2', '3.5', 'Ahsan', '5'], dtype='<U32')

In [293]:
b = [1,2,3.5,5]
b

[1, 2, 3.5, 5]

In [294]:
np.array(b)

array([1. , 2. , 3.5, 5. ])

In [295]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [296]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Generation Function

In [298]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [299]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [300]:
arr  = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [301]:
arr  =  np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

## Random Generation Function

In [303]:
np.random.rand(10)        # Normalization Between 0 to 1 Random Numbers

array([0.7659478 , 0.8616603 , 0.84931033, 0.03774763, 0.44403825,
       0.83428352, 0.62121054, 0.68953244, 0.05982085, 0.58144259])

In [304]:
np.random.randn(10)       # Standerlization Between -3 to 3

array([ 0.82377159, -1.35493919, -0.32891596,  1.54107136,  0.04423633,
       -0.57159523, -2.76351089,  0.49187852, -1.43873052, -0.24652397])

In [305]:
np.random.randint(6)   # Only one Number Generate 0 to 6 

3

In [306]:
np.random.randint(10,20)   # Only 10 Number are Generate Between the 10 To 20 Number 

18

# Array Attribute's  
(Not Calling() Attribute Its Not Like a Python Methods its a Attribute )

In [308]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [309]:
arr.shape   # 3 Rows and 3 Colums

(3, 3)

In [310]:
arr.size   #  how many element

9

In [311]:
arr.dtype

dtype('int32')

## Array Methods
Calling a Function () Its to not Like a Python and Numpy Attribute

In [313]:
arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [314]:
arr.min()

1

In [315]:
arr.max()

9

In [316]:
arr.sum()  # 1 to 9 all elements are sum

45

In [317]:
np.sum(arr,axis=0)  # Columns Vise Sum  Because of '0' axis

array([12, 15, 18])

In [318]:
np.sum(arr,axis=1)  # Rows Vise Sum  Because of '1' axis


array([ 6, 15, 24])

In [319]:
arr.mean()   # Middle Element

5.0

In [320]:
arr.std()    # Standard divension

2.581988897471611

In [321]:
arr.argmax()   # Max Number index Number

8

In [322]:
arr.argmin()   # Minimum Numer Index Number

0

## Reshaping and Resizing

In [324]:
arr  = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [325]:
arr.reshape(6,5)                   # 6 Row and 5 Colums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Array Indexing and Slicing of Vectors 

In [327]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [328]:
arr[6]  # Indexing Number 

17

In [329]:
arr[0:6]          # Slicing 

array([11, 12, 13, 14, 15, 16])

In [330]:
arr_slice=  arr[3::2]
arr                                          # 3 Index to last index and 2 step are gap between the value

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Numpy Indexing and Slicing of Matrix


In [332]:
arr  =  np.arange(1,31).reshape(6,5)
arr                                         #  There How Many Rows and colums  : (6Row and 5 Coloumns)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Indexing

In [334]:
arr[0]

array([1, 2, 3, 4, 5])

In [335]:
arr[5,4]

30

### Slicing

In [337]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [338]:
slice  = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [339]:
arr[:,2]              # only Coloumns are Select

array([ 3,  8, 13, 18, 23, 28])

## Boolean Indexing

In [341]:
arr  =  np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [342]:
bool_index  = arr % 2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [343]:
arr  =  arr[bool_index]
arr                                           # Even Elements

array([12, 14, 16, 18, 20])

# Array Operations
  - Operation are perform more than 2 values

## Arithematic Operation

In [347]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])    # Two Variable value are sum addition 

In [348]:
arr2 = a1 + a2
arr2

array([ 7,  9, 11, 13, 15])

In [349]:
arr3 = a1 - a2
arr3                    # Two Variable value are substraction addition 

array([-5, -5, -5, -5, -5])

## Broadcasting 

In [351]:
l = [10,20,30,40,50]
arr = np.array(l)

In [352]:
arr + 5

array([15, 25, 35, 45, 55])

In [353]:
arr2  =  np.arange(1,31).reshape(5,6)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [354]:
arr2 + 10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40]])

# Deep and Shallow Copy!

### Numpy Array Does not changes a Original array of python Numpy are separte location and id to changes to array


### Array changes and Slice are Another Location   && ALL array are changes so original array are also changes and new array 

### But ALL Array are not changes on original so one method are given that  "Copy()"

In [360]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### slice

In [362]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [363]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [364]:
a[4:6]*10

array([50, 60])

In [365]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [366]:
a
b= a

In [367]:
b[0] = 99

In [368]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [369]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [370]:
a
b = a.copy()

In [371]:
b[0]=100

In [372]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [373]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## Matrix Operation

In [375]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [376]:
A


array([[1, 2],
       [3, 4]])

In [377]:
B

array([[5, 6],
       [7, 8]])

In [378]:
A * B   # They are Multiply on INdexing 

array([[ 5, 12],
       [21, 32]])

### Matric Multiplication

In [416]:
A @ B

array([[19, 22],
       [43, 50]])

In [450]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

### Transpose

In [452]:
A.T

array([[1, 3],
       [2, 4]])

## Advanced Array Manipulation 

### Stacking Array (2 Arrays are Merged  Ya Joint)
 - 2 Matrix are not Stack
 - 2 Vector Mean one Dimension array Are Stack Possible

In [455]:
a = np.array([1,2,3,4])
b= np.array([5,6,7,8])

####  There are  3 Types of Stack 
  - Vertical Stack 
  - Horizontal Stack 
  - Simple Stack 

In [457]:
np.vstack((a,b))   # Vertical Stack only one Argument are Rescieved

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [458]:
np.hstack((a,b))      # Horizontal stack Only one Argument

array([1, 2, 3, 4, 5, 6, 7, 8])

In [459]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Splitting Array 
  - Horizontal Split
  - Vertical Split

In [461]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [462]:
np.hsplit(c,2)   # Horizontally Split 2 Parts are Split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [463]:
np.vsplit(c,2) # Vertically Split 2 Parts are Split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# Exercise Numpy Practice Project

## *** Valid Sudoko

In [470]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [479]:
s.sum()

405

#### ALl Rows are Sum 

In [482]:
b = np.sum(s,axis=1)      #          1 Axis are Row Define and sum are all Rows
b[b==45]

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [483]:
c = np.sum(s,axis=0)      #         0 Axis are Columns Define and sum are all Columns
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

### Every Block are Acess


In [488]:
s[0:3,0:3]     # Fisrt Blocl

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [490]:
s[0:3,3:6]    # 2nd blo

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [500]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [508]:
for i in range(0,9,3):                  # All Block are SUM 45
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


## General Question Base on Data Analysis

In [611]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [613]:
# - Get the shape of the matrix.

In [615]:
data.shape    # Shape is Instance Attribute

(5, 3)

In [617]:
# - Find the average age of students.

In [619]:
np.mean(data[:,0])

18.4

In [621]:
# - Extract Math marks of all students.

In [623]:
data[:,1]

array([85, 92, 76, 65, 90])

In [625]:
 # - Find the highest Science mark.

In [627]:
np.max(data[:,2])

95

In [629]:
#- Get details of the student who scored more than 90 in Math.

In [631]:
data[data[:,1] > 90]

array([[19, 92, 88]])

In [633]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [691]:
# - Increase Math marks of all students by 5.

In [693]:
 data[:,1] += 5
data

array([[ 18,  95,  78],
       [ 19, 102,  88],
       [ 17,  86,  95],
       [  0,   5,   0],
       [ 20, 100,  85]])

In [695]:
# - Find how many students are younger than 19.

In [697]:
len(data[data[:,0]<19])

3

In [699]:
#- Calculate the average marks in each subject (column-wise mean).

In [701]:
np.mean(data[:,1:],axis=0)

array([77.6, 69.2])

In [703]:
#- Get data of students who scored at least 80 in both subjects.

In [705]:
data[(data[:,1]>=80)& (data[:,2]>=80)]

array([[ 19, 102,  88],
       [ 17,  86,  95],
       [ 20, 100,  85]])

In [707]:
#- Replace all Science marks < 75 with 0.

In [709]:
data[:,2][data[:,2]<75] = 0

In [711]:
data

array([[ 18,  95,  78],
       [ 19, 102,  88],
       [ 17,  86,  95],
       [  0,   5,   0],
       [ 20, 100,  85]])